### ISSUE TITLE
html nodes were not removed at animation end

### ISSUE THREAD

**Issue by weijarz** [solidjs-community/solid-transition-group#10]
<https://codesandbox.io/s/solid-transition-jwm5g?file=/src/index.js>

Hit the button 10 times in quick, the state will be 'hidden', but the nodes still exists.

Both chrome and firefox has this problem.

**Comment by SanichKotikov** [comment]
Not sure about above example, but exit animation and removing nodes have stopped working in `0.0.9` (0.0.8 works fine for me)

**Comment by ryansolid** [comment]
Try 0.0.10... 0.0.9 was very broken. A bunch of PRs over a long period of time that seemed to fix certain issues but broke others. Hmm 0.0.10 isn't smooth either... tempted to revert back to 0.0.8 as it worked fine for all the cases I had, but feels bad to undo a bunch of "fixes".

**Comment by SanichKotikov** [comment]
`0.0.10` has the same result + it added flickering on enter animation.

**Comment by iainmerrick** [comment]
This bug still seems to exist in 0.0.12

Could it be related to Solid trying to recycle the nodes, for faster DOM updates?

If so, I'd be happy to take the performance hit of not doing any recycling (at least within a transition group) in exchange for reliable animations.

**Comment by ryansolid** [comment]
We don't recycle nodes. Only clone from a template that isn't used anywhere else. This is likely a timing issue.

**Comment by iainmerrick** [comment]
Ah, that's good to know! I'll let you know if I hit on a good repro case.

**Comment by thetarnav** [comment]
Pretty sure it doesn't happen anymore:
https://codesandbox.io/s/solid-transition-forked-0gqtxt?file=/src/index.js
Nodes that finish exiting are always removed from the DOM
