### ISSUE TITLE
Animation examples don't seem to work on the solid JS website

### ISSUE THREAD

**Issue by vivianeasley** [solidjs-community/solid-transition-group#16]
Hopefully I haven't missed something obvious. If so, I apologize in advance. The css animations example on the Solid JS website don't seem to work. It looks like maybe the solid-transition-group library isn't accessible: 
[https://www.solidjs.com/examples/cssanimations](https://www.solidjs.com/examples/cssanimations)

I love the idea of the library so I tried to get it working in a code sandbox but the description that it functions much like the FLIP technique isn't something I'm able to accomplish: 
[https://codesandbox.io/s/lucid-nobel-6hy9kb?file=/src/main.tsx:230-242](https://codesandbox.io/s/lucid-nobel-6hy9kb?file=/src/main.tsx:230-242)

If there's an obvious step being missed here it might be nice to mention it in the docs. Thanks in advance for your time!

**Comment by thetarnav** [comment]
Works again :)

**Comment by thetarnav** [comment]
Ok this issue is duplicated in multiple places, an it's most likely related to how the solid playground works. So I'm gonna close it and it could be continued here: https://github.com/solidjs/solid-site/issues/385
