### ISSUE TITLE
feature request: better documentation

### ISSUE THREAD

**Issue by illiaChaban** [solidjs-community/solid-transition-group#23]
Thank you for creating this library! I have used it many times and it's really nice. 
That being said I think the documentation could use a bit of work. I still don't understand the order of classNames applied and when to use which. I usually stick to onEnter/ onExit... methods, but it's also unclear what "done" method does. When I get it working, it takes a ton of trial and error

Based on my experience when "done' is called in the onExit phase, that's when the exiting element is actually removed, unless "done" from the onEnter phase called first (race condition of animations), then "done" from onEnter phase is what removes exiting element

It would be nice if the lib had some JSDOC comments for ease of reference. 
In fact, I think most of solid libraries could use JSDOC and I think there even might be a way to generate frontend documentation from JSDOC comments to keep then in sync

**Comment by Bersaelor** [comment]
For me, a few more examples of how it's intended to be used would be great.

How do you use `onEnter/ onExit` exactly, for example?

Maybe we should start an examples page somewhere.
