### ISSUE TITLE
is this maintained?

### ISSUE THREAD

**Issue by MisileLab** [solidjs-community/solid-transition-group#41]
just curious, It has no commits for 5 months and have no notice about maintain status

**Comment by thetarnav** [comment]
kinda
generally it’s a “complete” library
it just works™️
next major changes will probably come when solid 2.0 is released, which will hopefully to close the remaining issue with out-in (#34)
I’m not planning to do any bigger changes until then, maybe besides bugfixes if possible

**Comment by MisileLab** [comment]
> kinda
> generally it’s a “complete” library
> it just works™️
> next major changes will probably come when solid 2.0 is released, which will hopefully to close the remaining issue with out-in (#34)
> I’m not planning to do any bigger changes until then, maybe besides bugfixes if possible

ok I got it
(This library is really good btw)
