### ISSUE TITLE
Multiple Transition groups with same same items

### ISSUE THREAD

**Issue by odama626** [solidjs-community/solid-transition-group#46]
when using multiple transition groups with the same items in each one the animation or addition / remove always get applied to the last transition group on the page

**Comment by thetarnav** [comment]
Could you provide a peace of code to reproduce that?
I’m a bit confused by what you mean by “same items”.

**Comment by odama626** [comment]
I created a minimal example to try and reproduce it... and I wasn't able to... but oddly enough I can't reproduce it in my codebase now either

https://stackblitz.com/edit/solidjs-templates-hhmuax?file=src%2FApp.tsx

originally, when clicking something in "top" it would show up in "bottom" and not leave "top".. but yeah I can't reproduce it.

sorry about that
