### ISSUE TITLE
SSR support

### ISSUE THREAD

**Issue by beckend** [solidjs-community/solid-transition-group#7]
currently does not work

**Comment by ryansolid** [comment]
Hmm..whats the expected behavior? Basically identity? Like pass through without touching anything? I wasn't sure what to do with this one as obviously the browser behavior is specific to the DOM.

**Comment by beckend** [comment]
`solidJs.children is not a function` is what i get, this is from the node server.

```javascript
<Transition exitClass={styles.overlayLoadingDone}>
  {getInitialPageLoaded() && <Circles classes={styles.overlay} />}
</Transition>
```

The same code works fine without SSR

**Comment by beckend** [comment]
on a related topic, this is what i did when hydrating from SSR:

```javascript
<div ref=(r) =>{
  setTimeout((r) => { r.remove()}, 2000)
} />
```

giving it a generous amount of time to render, this works fine in non SSR, but hydrating i can console log the ref just fine but the element is not removed, i suspect there are some old ref which was being removed since the console did not error.
